import { BORDER_POSTS_CLASSNAMES } from "constants/classnames";
import Image from "next/image";
import mergeClasses from "utils/mergeClasses";

/**
 * Props for the Essay component.
 */
export interface EssayProps {
  /**
   * Custom class names passed to the root element.
   */
  className?: string;
  // children: React.ReactNode | React.ReactNode[] | string;
  name?: string;
  postTitle?: string;
}

/**
 * Essay Component
 */
export default function Essay({
  className,
  name = "",
  postTitle = "",
}: EssayProps): JSX.Element {
  return (
    <div className={mergeClasses(...BORDER_POSTS_CLASSNAMES, "col-span-4")}>
      <div className="grid grid-flow-row place-content-around grid-rows-6 grid-cols-1 w-full">
        <div className="grid grid-flow-col place-content-between pt-[18px] px-[18px]   row-span-1  col-span-1 ">
          <div>
            <h1 className="font-visuelt  w-fit align-middle  text-[#F2F2F270] text-[18px] font-normal leading-[24px]">
              Post - {name}
            </h1>
          </div>
          <div>
            <img
              src="assets/arrow.svg"
              className="align-start self-start mt-[-6px] cursor-pointer hover:scale-[101%] transition-all duration-500 ease-in-out"
              draggable="false"
            ></img>
          </div>
        </div>
        <div className=" grid grid-flow-row  row-span-6 h-full w-full  overflow-hidden ">
          <div className="bg-[#F5F5F5] border-[#EBEBEB] bg-paper border-2 rounded-t-[1px] shadow-sm gap-1  shadow-white mx-[80px] grid grid-flow-row items-start place-items-start ">
            <div className="backdrop:backdrop-blur-[500%] backdrop:backdrop-brightness-[50%]  h-full w-full block bg-white bg-opacity-80 px-10 pt-[16px]">
              <p className="text-[14px] font-light font-inter text-[#707070]  leading-[18.2px] tracking-[-0.07px] text-justify pt-[20px]">
                Date published: 01/10/2023
              </p>
              <h1 className="text-black font-inter font-semibold text-[26px] mt-[-5px]">
                {postTitle}
              </h1>
              <p className="text-[14px] font-light font-inter text-[#707070] pt-[10px]  leading-[18.2px] tracking-[-0.07px] text-justify">
                We discuss analogs based on elliptic curves over finite fields
                of public key cryptosystems which use the multiplicative group
                of a finite field. These elliptic curve cryptosystems may be
                more secure, because the analog of the discrete logarithm
                problem on elliptic curves is likely to be harder than the
                classical discrete logarithm problem, especially over GF(2").
              </p>
              <Image
                className="w-[150px] h-[100px] mx-auto object-fill grayscale hover:grayscale-0"
                src={"/podsfy-selection.png"}
                alt="asd"
                width={1920}
                height={1080}
                quality={100}
              ></Image>
              <p className="text-[14px] font-light font-inter text-[#707070] pt-[10px]  leading-[18.2px] tracking-[-0.07px] text-justify">
                We discuss the question of primitive points on an elliptic curve
                modulo p, and give a theorem on nonsmoothness of the order of
                the cyclic subgroup generated by a global point.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

Essay.displayName = "Essay";
