import { BORDER_POSTS_CLASSNAMES } from "constants/classnames";
import Image from "next/image";
import mergeClasses from "utils/mergeClasses";

/**
 * Props for the Essay component.
 */
export interface EssayProps {
  /**
   * Custom class names passed to the root element.
   */
  className?: string;
  // children: React.ReactNode | React.ReactNode[] | string;
}

/**
 * Essay Component
 */
export default function Essay({ className }: EssayProps): JSX.Element {
  return (
    <div className={mergeClasses(...BORDER_POSTS_CLASSNAMES, "col-span-4")}>
      <div className="grid grid-flow-row place-content-around grid-rows-6 grid-cols-1 w-full">
        <div className="grid grid-flow-col place-content-between pt-[18px] px-[18px]   row-span-1  col-span-1 ">
          <div>
            <h1 className="font-visuelt  w-fit align-middle  text-[#F2F2F270] text-[18px] font-normal leading-[24px]">
              Essays - podsfy.com
            </h1>
          </div>
          <div>
            <img
              src="assets/arrow.svg"
              className="align-start self-start mt-[-6px] cursor-pointer hover:scale-[101%] transition-all duration-500 ease-in-out"
              draggable="false"
            ></img>
          </div>
        </div>
        <div className=" grid grid-flow-row  row-span-6 w-full  overflow-hidden ">
          <div className="bg-[#F5F5F5] border-[#EBEBEB] border-2 rounded-t-[6px]   shadow-sm gap-1 px-10 pt-[40px] shadow-white mx-[110px] grid grid-flow-row items-start place-items-start h-fit py-3">
            <div> </div>
            <h1 className="text-black font-inter font-semibold text-[26px]">
              The Guiding Principle
            </h1>
            <p className="text-[14px] font-light font-inter text-[#707070] leading-[18.2px] tracking-[-0.07px] text-justify">
              We discuss analogs based on elliptic curves over finite fields of
              public key cryptosystems which use the multiplicative group of a
              finite field. These elliptic curve cryptosystems may be more
              secure, because the analog of the discrete logarithm problem on
              elliptic curves is likely to be harder than the classical discrete
              logarithm problem, especially over GF(2"). We discuss the question
              of primitive points on an elliptic curve modulo p, and give a
              theorem on nonsmoothness of the order of the cyclic subgroup
              generated by a global point.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

Essay.displayName = "Essay";
